### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by avalla** [avalla/trivia-game#1]
- [ ] Migrate html elements to components, creating a component library for project
- [ ] Improve backend error management (log errors)
- [ ] End to end testing with Cypress
